export const homeData = {
  title: [
    "Full Stack Engineer 🚀 Code to Cloud",
    1500,
    "React + Vue Virtuoso ⚛️🌊",
    1500,
    "Express & NestJS Backend Ninja 🥷",
    1500,
    "Tailwind & MUI Design Beast 🎨 Sleek UIs Delivered",
    1500,
    "Python & Django Pro 🐍 API Architect",
    1500,
    "Flask Whisperer 🔥 Lightweight, Powerful Backends",
    1500,
    "AI + LLMs Tamer 🤖 Smarter Web Experiences",
    1500,
    "Chatbot Builder 💬 Real Conversations, Real Results",
    1500,
    "Web3 Engineer 🕸️ Dapps Done Right",
    1500,
    "Performance-Centric Dev ⚡ Fast. Scalable. Clean.",
    1500,
  ],
};
